# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 13:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('country', models.CharField(default=b'', max_length=30)),
                ('region', models.CharField(default=b'', max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localgag.Reply')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='localgag.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_filename', models.CharField(max_length=50)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='localgag.Comment')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='localgag.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(default=b'', max_length=5)),
                ('radius', models.IntegerField(default=5)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='localgag.Location')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localgag.Status'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localgag.User'),
        ),
    ]
